"use strict";

// generated by dot.pegjs
var parser = require("./dot.js");

function parse(doc, file) {
  try {
    return parser.parse(file.contents || doc);
  } catch (err) {
    file.fail(err.message, err.location, "redot-parse");
  }
}

function parserFactory() {
  this.Parser = parse;
}

parserFactory.Parser = parse;

module.exports = parserFactory;
