"use strict";

// generated by dot.pegjs
var parser = require("./dot.js");

function parse(doc, file) {
  try {
    return {
      type: "Root",
      children: parser.parse(file.contents || doc)
    };
  } catch (err) {
    file.fail(err);
  }
}

function parserFactory() {
  this.Parser = parse;
}

parserFactory.Parser = parse;

module.exports = parserFactory;
